### ISSUE TITLE
Allow for unicoloured icon / allow for disabling icon

### ISSUE THREAD

**Issue by kithairon** [Quorafind/Obsidian-Daily-Notes-Editor#25]
### Feature Requested

Greatly useful plug-in! Thank you.  Was hoping for something like that for a while. 
My only little nag: the colourful icon stands out in the ribbon. Any chance that this could be made to blend in more? Or disabled? What you see in the screenshots is the Minimal theme. (The effect is no less garish in the default theme). Thanks fo r your efforts. 

### Relevant Screenshot

![screenshot](https://user-images.githubusercontent.com/1436817/205750381-470cc997-1bf8-4832-83a7-f50eac4f553f.jpg)

![light](https://user-images.githubusercontent.com/1436817/205750837-9d433eca-f171-4e38-bd84-e882cf7e417a.jpg)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by TeonaMonugo** [comment]
I join the request to add the ability to make the icon the same color as the rest. I couldn't do it myself through css.

**Comment by sbc** [comment]
Here's what I did to help this plugin work better with the theme I'm using (Prism). It's mostly reverting to defaults so should work with most themes.

1. Create a file (eg. daily-notes-editor.css) in [vault]/.obsidian/snippets
2. Add the following code to the file:

```css
.daily-note-title {
  color: unset !important;
}
.daily-note-title:hover {
  background-color: unset !important;
}
.svg-icon.daily-note svg path {
  stroke: var(--icon-color) !important;
}
.svg-icon.daily-note svg g path {
  fill: var(--icon-color) !important;
  stroke: var(--ribbon-background) !important;
  stroke-width: var(--icon-l-stroke-width) !important;
}
```

3. Turn on the snippet in Settings > Appearance.

![CleanShot 2023-02-08 at 17 11 43@2x](https://user-images.githubusercontent.com/101749/217673906-2d2cc44b-c17c-429f-902e-8485e69d81ca.png)
